export const ACTIVITY_LISTS = "ACTIVITY_LISTS";
export const POINTS_OF_INTEREST = "POINTS_OF_INTEREST";
export const ADD_TO_BOARD = "ADD_TO_BOARD";
export const REMOVE_FROM_BOARD = "REMOVE_FROM_BOARD";
